---
name: Ansible Galaxy
on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
    tags:
      - "*"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  molecule:
    uses: ./.github/workflows/molecule.yml

  galaxy:
    name: Galaxy
    runs-on: ubuntu-latest
    needs: molecule
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
